version : '3'
services:

  dingyangmall-mysql:
    build:
      context: .
      dockerfile: mysql-dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    restart: always
    container_name: dingyangmall-mysql
    image: dingyangmall-mysql
    ports:
      - 3306:3306
    privileged: true
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: --lower_case_table_names=1

  dingyangmall-redis:
    container_name: dingyangmall-redis
    image: redis
    build:
      context: .
      dockerfile: redis-dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/home/dingyangmall/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/dingyangmall/redis/redis.conf
  dingyangmall-nginx:
    container_name: dingyangmall-nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx-dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dist:/home/dingyangmall/projects/dingyangmall-ui
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - dingyangmall-server
    links:
      - dingyangmall-server
  dingyangmall-server:
    container_name: dingyangmall-server
    build:
      context: .
      dockerfile: dingyangmall-dockerfile
    ports:
      - "7500:7500"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dingyangmall/logs:/home/dingyangmall/logs
      - ./dingyangmall/uploadPath:/home/dingyangmall/uploadPath
    depends_on:
      - dingyangmall-mysql
      - dingyangmall-redis
    links:
      - dingyangmall-mysql
      - dingyangmall-redis
